### ISSUE TITLE
can't install on windows

### ISSUE THREAD

**Issue by xiaodiu** [monkeycz/python.js#3]
npm install python.js 
failed with following error:
C:\Users\username\AppData\Roaming\npm\node_modules\python.js>if not defined npm_c
onfig_node_gyp (node "E:\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_mo
dules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
'python-config' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
gyp: Call to 'python-config --libs' returned exit status 1 while in binding.gyp.
 while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (E:\nodejs\node_modules\npm\node_mod
ules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:204:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "E:\nodejs\node.exe" "E:\nodejs\node_modules\npm\node_mod
ules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\username\AppData\Roaming\npm\node_modules\python.js
gyp ERR! node -v v6.1.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "E:\nodejs\node.exe" "E:\nodejs\node_modules\npm\bin\npm-cl
i.js" "install" "python.js" "-g"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! python.js@0.5.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the python.js@0.5.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the python.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs python.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls python.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\username\npm-debug.log

then i am trying to pip install python-config
i still get above error

so here is my question
how to install python.js in windows?

**Comment by xiaodiu** [comment]
问题解决了。最后是从git上拉下代码后，在本地node-gyp configure然后再编译的。
